### ISSUE TITLE
RSS feed outputting an error

### ISSUE THREAD

**Issue by damcclean** [brendt/stitcher.io#58]
When you visit the RSS feed, a PHP error is returned: https://www.stitcher.io/rss

```
Fatal error: Uncaught Error: Class 'PhpOption\Option' not found in /home/forge/aggregate.stitcher.io/releases/20200131-142225/vendor/laravel/framework/src/Illuminate/Support/Env.php:100 Stack trace: #0 /home/forge/aggregate.stitcher.io/releases/20200131-142225/vendor/laravel/framework/src/Illuminate/Support/helpers.php(265): Illuminate\Support\Env::get() #1 /home/forge/stitcher.io/src/config.php(6): env() #2 /home/forge/stitcher.io/vendor/pageon/stitcher-core/src/Pageon/Config.php(83): require('/home/forge/sti...') #3 /home/forge/stitcher.io/vendor/pageon/stitcher-core/src/Pageon/Config.php(40): Pageon\Config::load() #4 /home/forge/stitcher.io/vendor/pageon/stitcher-core/src/Stitcher/App.php(25): Pageon\Config::init() #5 /home/forge/stitcher.io/public/index.php(11): Stitcher\App::init() #6 {main} thrown in /home/forge/aggregate.stitcher.io/releases/20200131-142225/vendor/laravel/framework/src/Illuminate/Support/Env.php on line 100
```

**Comment by brendt** [comment]
Thanks for letting me know, it's fixed!
